// Generated by CoffeeScript 1.6.1
(function() {
  var childWindows, closeChildWindows, numberOfWindowsToOpen, originalRunTestsEverywhere, recorded_arguments, runBeforeTests, runTests,
    __slice = [].slice;

  originalRunTestsEverywhere = Meteor._runTestsEverywhere;

  recorded_arguments = null;

  Meteor._runTestsEverywhere = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return recorded_arguments = args;
  };

  runTests = function() {
    if (recorded_arguments == null) {
      throw new Error("test-in-browser hasn't called _runTestsEverywhere yet");
    }
    return originalRunTestsEverywhere.apply(null, recorded_arguments);
  };

  runBeforeTests = null;

  numberOfWindowsToOpen = 0;

  childWindows = [];

  Meteor.windowtest = {
    numberOfWindowsToOpen: function(n) {
      return numberOfWindowsToOpen = n;
    },
    beforeTests: function(f) {
      if (runBeforeTests != null) {
        throw new Error("Can't call beforeTests more than once");
      }
      return runBeforeTests = f;
    }
  };

  Template.begin_tests.events({
    'click #begin-tests-button': function() {
      var i, _i;
      $('#begin-tests-div').hide();
      if (numberOfWindowsToOpen >= 1) {
        for (i = _i = 1; 1 <= numberOfWindowsToOpen ? _i <= numberOfWindowsToOpen : _i >= numberOfWindowsToOpen; i = 1 <= numberOfWindowsToOpen ? ++_i : --_i) {
          childWindows[i] = window.open("/child" + i, "child" + i, 'menubar=yes,toolbar=yes,location=yes,resizable=yes,scrollbars=yes,status=yes');
        }
      }
      if (runBeforeTests != null) {
        return runBeforeTests(function() {
          return runTests();
        });
      } else {
        return runTests();
      }
    }
  });

  Template.begin_tests.show = function() {
    return window.location.pathname === '/';
  };

  closeChildWindows = function() {
    return Meteor.BrowserMsg.send('close windows');
  };

  Meteor.autorun(function(handle) {
    if (!Template.test_table.running() && Template.test_table.passed()) {
      handle.stop();
      return closeChildWindows();
    }
  });

  if (window.location.pathname !== '/') {
    Meteor.BrowserMsg.listen({
      'close windows': function() {
        return window.close();
      }
    });
  }

}).call(this);
